public enum TileSpecialAction {
    ADDFOX,
    ADDROLL,
    ADDADDITIONALDICE,
    ADDRANDOMBLUE,
    ADDRANDOMYELLOW,
    ADDRANDOMGREEN,
    ADDPURPLE6,
    ADDORANGE4,
    ADDORANGE5,
    ADDORANGE6,
}
